Repository Zmbackup/zmbackup, pull requests merged in 2018-09, with the labels that each got.

#112 Some adjusts
  installScript/deploy.sh
  installScript/vars.sh
  project/lib/bash/ParallelAction.sh
Labels: Bug Report, Question

#111 Fix ldap_filter function and migration to TXT
  project/lib/bash/BackupAction.sh
  project/lib/bash/MigrationAction.sh
  project/lib/bash/ParallelAction.sh
Labels: Bug Report, Feature Idea

#114 fix delete_old to actually delete older backups
  project/lib/bash/DeleteAction.sh
Labels: Bug Report
